config/routes.rb
Rails.application.routes.draw do
  get '/articles', to: 'articles#index'
  get '/articles/new', to: 'articles#new', as: 'new_article'
  post '/articles', to: 'articles#create', as: 'create_article' 
  get '/articles/:id', to: 'articles#show', as: 'show_article'
  get '/articles/:id/edit', to: 'articles#edit', as: 'edit_article'
  patch '/articles/:id', to: 'articles#update', as: 'update_article'
  delete '/articles/:id', to: 'articles#destroy', as: 'delete_article'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article_sample.rb
class ArticleSample < ApplicationRecord
    validates :name, presence: true,
                     uniqueness: true  
    validates :age, presence: true
    validates :body, presence: true,
                    length: {minimum: 5} 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    def index
        @articles = ArticleSample.all
    end

    def show
        @article = ArticleSample.find(params[:id])
    end

    def new
        @article = ArticleSample.new
    end

    def create
        @article = ArticleSample.new(article_params)
        if @article.save
           redirect_to articles_path(@article)
        else
            render :new
        end
    end

    def edit
        @article = ArticleSample.find(params[:id])
    end

    def update
        @article = ArticleSample.find(params[:id])
        if @article.update(article_params)
            redirect_to articles_path(@article)
        else
            render :edit
        end  
    end
    
    def destroy
        @article = ArticleSample.find(params[:id])
        @article.destroy
        redirect_to articles_path(@article)
    end
    
    private
  
    def article_params
        params.require(:article).permit(:name, :body, :age)
    end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>EDIT</h1>
<section class="new">       
        <div>
            <% if @article.errors.any? %>
                <ul>
                    <% @article.errors.full_messages.each do |message| %>
                        <li>
                            <%= message %>
                        </li>
                    <% end %> 
                </ul>
            <% end %> 
        </div>

    <%= form_with scope: :article, url: update_article_path, method: :patch, local: true do |f|%>      
        <p>
            <div class="label">
                <%= f.label :name, class:'font' %>
                <%= f.text_field :name, class:'field'%>
            </div>
            <div class="label">
                <%= f.label :age, class:'font' %>
                <%= f.text_field :age, class:'field'%>
            </div>
            <div class="label">
                <%= f.label :body, class:'font' %>
                <%= f.text_area :body, size: "30x8", class:'field' %>
            </div>
            <div class = "actions">
               <%= f.submit 'Update', class: 'button'%>
            </div>  
        </p>   
    <% end %>
</section>

app/views/articles/index.html.erb
    <h1>Agent List</h1>
    <div class = "section">
    <table>
        <thead>
            <tr>    
                <th>NAME</th>
                <th>AGE</th>
                <th>BIOGRAPHY</th>
          </tr>
        </thead>
    <tbody>
        <% @articles.each do |article| %>
            <tr>
                <td><%= article.name %></td>
                <td><%= article.age %></td>
                <td><%= article.body %></td>
                <td><%= link_to 'Show',show_article_path(article) %></td>
                <td><%= link_to 'Edit',edit_article_path(article) %></td>
                <td><%= link_to 'Delete',delete_article_path(article), method: :delete, data: {confirm: "Are you sure?" } %></td>
            </tr>   
        <% end %>
    </tbody>
    </table>
     <div>
    <button><%= link_to 'Add new Agent', new_article_path %>

app/views/articles/new.html.erb
<h1>AGENT</h1>

<section class="new">
        <div>
            <% if @article.errors.any? %>
                <ul>
                    <% @article.errors.full_messages.each do |message| %>
                        <li>
                            <%= message %>
                        </li>
                    <% end %> 
                </ul>
            <% end %> 
        </div>
    
    <%= form_with scope: :article, url: create_article_path, local:true do |f| %>
        <p>
            <div class="label">
                <%= f.label :name, class:'font' %>
                <%= f.text_field :name, class:'field'%>
            </div>
            <div class="label">
                <%= f.label :age, class:'font' %>
                <%= f.text_field :age, class:'field'%>
            </div>
            <div class="label">
                <%= f.label :body, class:'font' %>
                <%= f.text_area :body, size: "30x8", class:'field' %>
            </div>
            <div class = "actions">
                <%= f.submit 'Create', class: 'button'  %>
            </div>
        </p>
    <% end %>
</section>

app/views/articles/show.html.erb
<h1>Agent Details</h1>
<section class="show">  
<p><strong>Name:</strong>  <%= @article.name%></p>
<p><strong>Age:</strong>  <%= @article.age%></p>
<p><strong>Biography:</strong> <%= @article.body%> </p>
</section>
<button class ="showButton"><%= link_to 'Edit', edit_article_path %></button>
<button class ="backButton"><%= link_to 'Back', articles_path %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>